package GamePlay0;
import Playerpkg.Player;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.colorchooser.ColorSelectionModel;

public class NewJFrame1 extends javax.swing.JFrame {
    private int NumOfPlayer ;
    private Player[] player ;
    private boolean hint = false;
    private boolean isPlayAgain;

    public void setIsPlayAgain(boolean isPlayAgain) {
        this.isPlayAgain = isPlayAgain;
    }
    
    public NewJFrame1() throws InterruptedException {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        player = new Player[6];
        for (int i=0;i<6;i++){
            player[i] = new Player();
        }
     
        
       noOFplayer_pnl.setVisible(false);
       jColorChooser1.setVisible(false);
       player1_btn.setVisible(false);
       player2_btn.setVisible(false);
       player3_btn.setVisible(false);
       player4_btn.setVisible(false);
       player5_btn.setVisible(false);
       player6_btn.setVisible(false);
       pic1.setImage("src/Gameplay/img/monopoly.png", false);
       pic2.setImage("src/Gameplay/img/hat.png", false);
       pic3.setImage("src/Gameplay/img/hat.png", false);
       pic4.setImage("src/Gameplay/img/hat.png", false);
       pic5.setImage("src/Gameplay/img/hat.png", false);
       pic6.setImage("src/Gameplay/img/hat.png", false);
       pic7.setImage("src/Gameplay/img/hat.png", false);
       pic8.setImage("src/Gameplay/img/hat.png", false);
       pic9.setImage("src/Gameplay/img/hat.png", false);
       pic10.setImage("src/Gameplay/img/hat.png", false);
       pic11.setImage("src/Gameplay/img/hat.png", false);
       pic12.setImage("src/Gameplay/img/hat.png", false);
       pic13.setImage("src/Gameplay/img/hat.png", false);
       pic14.setImage("src/Gameplay/img/hat.png", false);
       pic15.setImage("src/Gameplay/img/hat.png", false);
       pic16.setImage("src/Gameplay/img/hat.png", false);
       pic17.setImage("src/Gameplay/img/hat.png", false);
       pic18.setImage("src/Gameplay/img/hat.png", false);
       pic19.setImage("src/Gameplay/img/hat.png", false);
       pic20.setImage("src/Gameplay/img/hat.png", false);
       pic21.setImage("src/Gameplay/img/hat.png", false);
       pic22.setImage("src/Gameplay/img/hat.png", false);
       pic23.setImage("src/Gameplay/img/hat.png", false);
       pic24.setImage("src/Gameplay/img/hat.png", false);
       
      
    }    
    public int getNumOfPlayer() {
        return NumOfPlayer;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start_btn = new javax.swing.JButton();
        NoOFplayer_btn = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        player1_btn = new javax.swing.JButton();
        player2_btn = new javax.swing.JButton();
        player4_btn = new javax.swing.JButton();
        player3_btn = new javax.swing.JButton();
        player5_btn = new javax.swing.JButton();
        player6_btn = new javax.swing.JButton();
        jColorChooser1 = new javax.swing.JColorChooser();
        noOFplayer_pnl = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        Hint_lbl = new javax.swing.JLabel();
        pic2 = new GamePlay0.pic();
        pic3 = new GamePlay0.pic();
        pic4 = new GamePlay0.pic();
        pic5 = new GamePlay0.pic();
        pic6 = new GamePlay0.pic();
        pic7 = new GamePlay0.pic();
        pic8 = new GamePlay0.pic();
        pic9 = new GamePlay0.pic();
        pic10 = new GamePlay0.pic();
        pic11 = new GamePlay0.pic();
        pic12 = new GamePlay0.pic();
        pic13 = new GamePlay0.pic();
        pic14 = new GamePlay0.pic();
        pic15 = new GamePlay0.pic();
        pic16 = new GamePlay0.pic();
        pic17 = new GamePlay0.pic();
        pic18 = new GamePlay0.pic();
        pic19 = new GamePlay0.pic();
        pic20 = new GamePlay0.pic();
        pic21 = new GamePlay0.pic();
        pic22 = new GamePlay0.pic();
        pic23 = new GamePlay0.pic();
        pic24 = new GamePlay0.pic();
        pic1 = new GamePlay0.pic();
        DetectDice = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        start_btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        start_btn.setText("Start Game");
        start_btn.setPreferredSize(new java.awt.Dimension(80, 25));
        start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_btnActionPerformed(evt);
            }
        });

        NoOFplayer_btn.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        NoOFplayer_btn.setText("Number of Players");
        NoOFplayer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoOFplayer_btnActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jButton8.setText("EXIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        player1_btn.setText("player1");
        player1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1_btnActionPerformed(evt);
            }
        });

        player2_btn.setText("player2");
        player2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2_btnActionPerformed(evt);
            }
        });

        player4_btn.setText("player4");
        player4_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player4_btnActionPerformed(evt);
            }
        });

        player3_btn.setText("player3");
        player3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3_btnActionPerformed(evt);
            }
        });

        player5_btn.setText("player5");
        player5_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player5_btnActionPerformed(evt);
            }
        });

        player6_btn.setText("player6");
        player6_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player6_btnActionPerformed(evt);
            }
        });

        jColorChooser1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jColorChooser1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jColorChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jColorChooser1MouseClicked(evt);
            }
        });

        noOFplayer_pnl.setLayout(null);

        jRadioButton4.setText("4 Players");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        noOFplayer_pnl.add(jRadioButton4);
        jRadioButton4.setBounds(290, 180, 90, 23);

        jRadioButton2.setText("2 Players");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        noOFplayer_pnl.add(jRadioButton2);
        jRadioButton2.setBounds(70, 80, 100, 23);

        jRadioButton3.setText("3 Players");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        noOFplayer_pnl.add(jRadioButton3);
        jRadioButton3.setBounds(476, 80, 100, 23);

        jRadioButton5.setText("5 Players");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        noOFplayer_pnl.add(jRadioButton5);
        jRadioButton5.setBounds(77, 416, 90, 23);

        jRadioButton6.setText("6 Players");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        noOFplayer_pnl.add(jRadioButton6);
        jRadioButton6.setBounds(476, 416, 100, 23);

        Hint_lbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 18)); // NOI18N
        noOFplayer_pnl.add(Hint_lbl);
        Hint_lbl.setBounds(684, 131, 419, 35);

        javax.swing.GroupLayout pic2Layout = new javax.swing.GroupLayout(pic2);
        pic2.setLayout(pic2Layout);
        pic2Layout.setHorizontalGroup(
            pic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic2Layout.setVerticalGroup(
            pic2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic2);
        pic2.setBounds(100, 110, 50, 51);

        javax.swing.GroupLayout pic3Layout = new javax.swing.GroupLayout(pic3);
        pic3.setLayout(pic3Layout);
        pic3Layout.setHorizontalGroup(
            pic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic3Layout.setVerticalGroup(
            pic3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic3);
        pic3.setBounds(430, 110, 50, 51);

        javax.swing.GroupLayout pic4Layout = new javax.swing.GroupLayout(pic4);
        pic4.setLayout(pic4Layout);
        pic4Layout.setHorizontalGroup(
            pic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic4Layout.setVerticalGroup(
            pic4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic4);
        pic4.setBounds(490, 110, 50, 51);

        javax.swing.GroupLayout pic5Layout = new javax.swing.GroupLayout(pic5);
        pic5.setLayout(pic5Layout);
        pic5Layout.setHorizontalGroup(
            pic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic5Layout.setVerticalGroup(
            pic5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic5);
        pic5.setBounds(550, 110, 50, 51);

        javax.swing.GroupLayout pic6Layout = new javax.swing.GroupLayout(pic6);
        pic6.setLayout(pic6Layout);
        pic6Layout.setHorizontalGroup(
            pic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic6Layout.setVerticalGroup(
            pic6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic6);
        pic6.setBounds(430, 290, 50, 50);

        javax.swing.GroupLayout pic7Layout = new javax.swing.GroupLayout(pic7);
        pic7.setLayout(pic7Layout);
        pic7Layout.setHorizontalGroup(
            pic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pic7Layout.setVerticalGroup(
            pic7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic7);
        pic7.setBounds(490, 290, 50, 51);

        javax.swing.GroupLayout pic8Layout = new javax.swing.GroupLayout(pic8);
        pic8.setLayout(pic8Layout);
        pic8Layout.setHorizontalGroup(
            pic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic8Layout.setVerticalGroup(
            pic8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic8);
        pic8.setBounds(280, 210, 50, 51);

        javax.swing.GroupLayout pic10Layout = new javax.swing.GroupLayout(pic10);
        pic10.setLayout(pic10Layout);
        pic10Layout.setHorizontalGroup(
            pic10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pic10Layout.setVerticalGroup(
            pic10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pic9Layout = new javax.swing.GroupLayout(pic9);
        pic9.setLayout(pic9Layout);
        pic9Layout.setHorizontalGroup(
            pic9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic9Layout.setVerticalGroup(
            pic9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic9);
        pic9.setBounds(340, 210, 50, 51);

        javax.swing.GroupLayout pic11Layout = new javax.swing.GroupLayout(pic11);
        pic11.setLayout(pic11Layout);
        pic11Layout.setHorizontalGroup(
            pic11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic11Layout.setVerticalGroup(
            pic11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic11);
        pic11.setBounds(280, 270, 50, 51);

        javax.swing.GroupLayout pic13Layout = new javax.swing.GroupLayout(pic13);
        pic13.setLayout(pic13Layout);
        pic13Layout.setHorizontalGroup(
            pic13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pic13Layout.setVerticalGroup(
            pic13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pic12Layout = new javax.swing.GroupLayout(pic12);
        pic12.setLayout(pic12Layout);
        pic12Layout.setHorizontalGroup(
            pic12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic12Layout.setVerticalGroup(
            pic12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic12);
        pic12.setBounds(340, 270, 50, 51);

        javax.swing.GroupLayout pic14Layout = new javax.swing.GroupLayout(pic14);
        pic14.setLayout(pic14Layout);
        pic14Layout.setHorizontalGroup(
            pic14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic14Layout.setVerticalGroup(
            pic14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic14);
        pic14.setBounds(30, 350, 50, 51);

        javax.swing.GroupLayout pic15Layout = new javax.swing.GroupLayout(pic15);
        pic15.setLayout(pic15Layout);
        pic15Layout.setHorizontalGroup(
            pic15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic15Layout.setVerticalGroup(
            pic15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic15);
        pic15.setBounds(90, 350, 50, 51);

        javax.swing.GroupLayout pic16Layout = new javax.swing.GroupLayout(pic16);
        pic16.setLayout(pic16Layout);
        pic16Layout.setHorizontalGroup(
            pic16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic16Layout.setVerticalGroup(
            pic16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic16);
        pic16.setBounds(150, 350, 50, 51);

        javax.swing.GroupLayout pic17Layout = new javax.swing.GroupLayout(pic17);
        pic17.setLayout(pic17Layout);
        pic17Layout.setHorizontalGroup(
            pic17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic17Layout.setVerticalGroup(
            pic17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic17);
        pic17.setBounds(60, 290, 50, 51);

        javax.swing.GroupLayout pic19Layout = new javax.swing.GroupLayout(pic19);
        pic19.setLayout(pic19Layout);
        pic19Layout.setHorizontalGroup(
            pic19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pic19Layout.setVerticalGroup(
            pic19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pic18Layout = new javax.swing.GroupLayout(pic18);
        pic18.setLayout(pic18Layout);
        pic18Layout.setHorizontalGroup(
            pic18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic18Layout.setVerticalGroup(
            pic18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic18);
        pic18.setBounds(120, 290, 50, 51);

        javax.swing.GroupLayout pic20Layout = new javax.swing.GroupLayout(pic20);
        pic20.setLayout(pic20Layout);
        pic20Layout.setHorizontalGroup(
            pic20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic20Layout.setVerticalGroup(
            pic20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic20);
        pic20.setBounds(430, 350, 50, 51);

        javax.swing.GroupLayout pic21Layout = new javax.swing.GroupLayout(pic21);
        pic21.setLayout(pic21Layout);
        pic21Layout.setHorizontalGroup(
            pic21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic21Layout.setVerticalGroup(
            pic21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic21);
        pic21.setBounds(40, 110, 50, 50);

        javax.swing.GroupLayout pic22Layout = new javax.swing.GroupLayout(pic22);
        pic22.setLayout(pic22Layout);
        pic22Layout.setHorizontalGroup(
            pic22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pic22Layout.setVerticalGroup(
            pic22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic22);
        pic22.setBounds(550, 290, 50, 50);

        javax.swing.GroupLayout pic23Layout = new javax.swing.GroupLayout(pic23);
        pic23.setLayout(pic23Layout);
        pic23Layout.setHorizontalGroup(
            pic23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic23Layout.setVerticalGroup(
            pic23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic23);
        pic23.setBounds(490, 350, 50, 51);

        javax.swing.GroupLayout pic24Layout = new javax.swing.GroupLayout(pic24);
        pic24.setLayout(pic24Layout);
        pic24Layout.setHorizontalGroup(
            pic24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pic24Layout.setVerticalGroup(
            pic24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        noOFplayer_pnl.add(pic24);
        pic24.setBounds(550, 350, 50, 51);

        javax.swing.GroupLayout pic1Layout = new javax.swing.GroupLayout(pic1);
        pic1.setLayout(pic1Layout);
        pic1Layout.setHorizontalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );
        pic1Layout.setVerticalGroup(
            pic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );

        DetectDice.setText("Detecting Dice With Camera");
        DetectDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetectDiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoOFplayer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(noOFplayer_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(player1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addComponent(player2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(55, 55, 55)
                                                .addComponent(player3_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(player4_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(46, 46, 46)
                                                .addComponent(player5_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(55, 55, 55)
                                                .addComponent(player6_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DetectDice, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(NoOFplayer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(noOFplayer_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(DetectDice)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player1_btn)
                                    .addComponent(player2_btn)
                                    .addComponent(player3_btn))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player4_btn)
                                    .addComponent(player5_btn)
                                    .addComponent(player6_btn))
                                .addGap(57, 57, 57)
                                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jColorChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jColorChooser1MouseClicked
        
       
    }//GEN-LAST:event_jColorChooser1MouseClicked

    public void setplayerColor(int idx){
         Color color =  jColorChooser1.getColor();
         System.out.println(color);
        
         int i=0;
         boolean choosed = false;
         while (i<6){
             
             if(color.equals(player[i].getM_color())){
                 Hint_lbl.setText("Please, Select anothor color !");
                
                 choosed = true;
             }
             i++;
         }
         if (choosed == false) player[idx].setM_color(color);
        

    }
    
    private void player1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1_btnActionPerformed
           // TODO add your handling code here:
         try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
            setplayerColor(0);
            player1_btn.setBackground(player[0].getM_color());
            player[0].setM_id(0);
           
        
    }//GEN-LAST:event_player1_btnActionPerformed

    private void player3_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3_btnActionPerformed
        // TODO add your handling code here:
         try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        setplayerColor(2);
        player3_btn.setBackground(player[2].getM_color());
        player[2].setM_id(2);
       
    }//GEN-LAST:event_player3_btnActionPerformed

    private void player5_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player5_btnActionPerformed
        // TODO add your handling code here:
         try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        setplayerColor(4);
        player5_btn.setBackground(player[4].getM_color());
        player[4].setM_id(4);
       
    }//GEN-LAST:event_player5_btnActionPerformed

    private void player2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2_btnActionPerformed
        // TODO add your handling code here:
         try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        setplayerColor(1);
        player2_btn.setBackground(player[1].getM_color());
        player[1].setM_id(1);
        
    }//GEN-LAST:event_player2_btnActionPerformed

    private void player4_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player4_btnActionPerformed
        // TODO add your handling code here:
         try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        setplayerColor(3);
        player4_btn.setBackground(player[3].getM_color());
        player[3].setM_id(3);
       
    }//GEN-LAST:event_player4_btnActionPerformed

    private void player6_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player6_btnActionPerformed
        // TODO add your handling code here:
         try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        setplayerColor(5);
        player6_btn.setBackground(player[5].getM_color());
        player[5].setM_id(5);
       
    }//GEN-LAST:event_player6_btnActionPerformed

    private void NoOFplayer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoOFplayer_btnActionPerformed
        noOFplayer_pnl.setVisible(true);
         try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NoOFplayer_btnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //this.dispose();
        System.exit(0);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
         try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
        player1_btn.setVisible(true);
        player2_btn.setVisible(true);
        player3_btn.setVisible(true);
        player4_btn.setVisible(true);
        player5_btn.setVisible(false);
        player6_btn.setVisible(false);
        jColorChooser1.setVisible(true);
        NumOfPlayer = 4;
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
        player1_btn.setVisible(true);
        player2_btn.setVisible(true);
        player3_btn.setVisible(false);
        player4_btn.setVisible(false);
        player5_btn.setVisible(false);
        player6_btn.setVisible(false);
        jColorChooser1.setVisible(true);
        NumOfPlayer = 2;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
        player1_btn.setVisible(true);
        player2_btn.setVisible(true);
        player3_btn.setVisible(true);
        player4_btn.setVisible(false);
        player5_btn.setVisible(false);
        player6_btn.setVisible(false);
        jColorChooser1.setVisible(true);
        NumOfPlayer = 3;
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
        player1_btn.setVisible(true);
        player2_btn.setVisible(true);
        player3_btn.setVisible(true);
        player4_btn.setVisible(true);
        player5_btn.setVisible(true);
        player6_btn.setVisible(false);
        
        jColorChooser1.setVisible(true);
        NumOfPlayer = 5;
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        try {
            SoundEffects.PlaySound("src/Gameplay/soundEffects/snd_sys_confirm.wav");
                    } catch (IOException ex) {
            Logger.getLogger(Gameplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(true);
        player1_btn.setVisible(true);
        player2_btn.setVisible(true);
        player3_btn.setVisible(true);
        player4_btn.setVisible(true);
        player5_btn.setVisible(true);
        player6_btn.setVisible(true);
        jColorChooser1.setVisible(true);
        NumOfPlayer = 6;
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_btnActionPerformed
        // TODO add your handling code here:
        if(!jRadioButton2.isSelected()&&!jRadioButton3.isSelected()&&!jRadioButton4.isSelected()&&!jRadioButton5.isSelected()&&!jRadioButton6.isSelected())
        {  NumOfPlayer = 2 ;
           player[0].setM_color(Color.WHITE);
           player[0].setM_id(0);
           player[1].setM_color(Color.GRAY);
           player[1].setM_id(1);
        }
        Gameplay g;
        try {
            //if (isPlayAgain) 
           //     g = new Gameplay();
           // else
            g = SingletoneGamePlay.getInstance(isPlayAgain);
            
            g.setNumbOfPlayers(NumOfPlayer);
            g.setPlayer(player);
            g.setDetectDice(DetectDice.isSelected());
            
            g.setExtendedState(JFrame.MAXIMIZED_BOTH);
            g.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
            this.dispose();
    }//GEN-LAST:event_start_btnActionPerformed
    File file = new File("detectIt.exe");     
    void DetectDice() throws IOException{
       
       if (! file.exists()) {
            throw new IllegalArgumentException("The file " + "detectIt.exe" + " does not exist");
        }
        Process p = Runtime.getRuntime().exec(file.getAbsolutePath());
    }
    Process p ;
    Robot r;
    private void DetectDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetectDiceActionPerformed
        if (DetectDice.isSelected()){
            DetectDice.setEnabled(false);
        try {
            p = Runtime.getRuntime().exec(file.getAbsolutePath());
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else {
            p.destroy();
            Robot r;
            try {
                r = new Robot();
                r.keyPress(KeyEvent.VK_ESCAPE);
            } catch (AWTException ex) {
                Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_DetectDiceActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewJFrame1().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DetectDice;
    private javax.swing.JLabel Hint_lbl;
    private javax.swing.JButton NoOFplayer_btn;
    private javax.swing.JButton jButton8;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JPanel noOFplayer_pnl;
    private GamePlay0.pic pic1;
    private GamePlay0.pic pic10;
    private GamePlay0.pic pic11;
    private GamePlay0.pic pic12;
    private GamePlay0.pic pic13;
    private GamePlay0.pic pic14;
    private GamePlay0.pic pic15;
    private GamePlay0.pic pic16;
    private GamePlay0.pic pic17;
    private GamePlay0.pic pic18;
    private GamePlay0.pic pic19;
    private GamePlay0.pic pic2;
    private GamePlay0.pic pic20;
    private GamePlay0.pic pic21;
    private GamePlay0.pic pic22;
    private GamePlay0.pic pic23;
    private GamePlay0.pic pic24;
    private GamePlay0.pic pic3;
    private GamePlay0.pic pic4;
    private GamePlay0.pic pic5;
    private GamePlay0.pic pic6;
    private GamePlay0.pic pic7;
    private GamePlay0.pic pic8;
    private GamePlay0.pic pic9;
    private javax.swing.JButton player1_btn;
    private javax.swing.JButton player2_btn;
    private javax.swing.JButton player3_btn;
    private javax.swing.JButton player4_btn;
    private javax.swing.JButton player5_btn;
    private javax.swing.JButton player6_btn;
    private javax.swing.JButton start_btn;
    // End of variables declaration//GEN-END:variables
}
